# See https://pre-commit.com/ for usage and config
repos:
- repo: local
  hooks:
  - id: format
    name: format
    stages: [commit]
    language: system
    entry: pipenv run black .
    pass_filenames: false
    types: [python]

  - id: lint
    name: lint
    stages: [commit]
    language: system
    entry: pipenv run flake8
    pass_filenames: false
    types: [python]

  - id: test
    name: test
    stages: [commit]
    language: system
    entry: pipenv run pytest
    pass_filenames: false
    types: [python]
