name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install brane CLI
        uses: romnn/setup-brane-action@master

      - name: Build the brane package
        run: |
          sudo $HOME/.local/bin/brane build container.yml
          sudo $HOME/.local/bin/brane list

      - name: Import training package
        shell: bash
        run: |
          (set -o pipefail && echo "import training;" | sudo $HOME/.local/bin/brane repl -c)

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
         
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      
      - name: Code checks
        uses: pre-commit/action@v2.0.0
        with:
          extra_args: --all-files
